# Generated by Django 4.0.4 on 2022-06-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
            preserve_default=False,
        ),
    ]
