# Generated by Django 4.0.4 on 2022-06-08 05:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=datetime.datetime(2022, 6, 8, 5, 28, 26, 56107, tzinfo=utc), upload_to='photos/products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=datetime.datetime(2022, 6, 8, 5, 28, 36, 764024, tzinfo=utc), upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
