# Generated by Django 4.0.4 on 2022-06-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
    ]
