# Generated by Django 4.0.4 on 2022-06-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_to',
        ),
    ]
