# Generated by Django 4.0.4 on 2022-06-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_discount_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricerange', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.filter_price'),
        ),
    ]
