# Generated by Django 4.0.4 on 2022-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_filter_price_product_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_range',
        ),
        migrations.DeleteModel(
            name='filter_price',
        ),
    ]
