# Generated by Django 4.0.4 on 2022-06-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_subject_reviewrating_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pricerange_from', models.IntegerField()),
                ('pricerange_to', models.IntegerField()),
            ],
        ),
    ]
