# Generated by Django 4.0.4 on 2022-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_order_note_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
