# Generated by Django 4.0.4 on 2022-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_address_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_totel',
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(null=True),
        ),
    ]
