# Generated by Django 4.0.4 on 2022-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_totel_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
