# Generated by Django 4.0.4 on 2022-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_address_order_id_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(),
        ),
    ]
