# Generated by Django 4.0.4 on 2022-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Out_For_Delivery', 'Out_For_Delivery'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='New', max_length=50),
        ),
    ]
